spring:
  application:
    name: payment-ms
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/database_spring?currentSchema=payment
    username: postgres
    password: 12345678
  flyway:
    defaultSchema: payment