spring:
  application:
    name: payment-ms
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/springbootdb?currentSchema=payment
    username: luis
    password: 12345
  flyway:
    defaultSchema: payment

server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka
  instance:
    instance-id: ${spring.application.name}:${random.int}

resilience4j:
  circuitbreaker:
    instances:
      updateOrder:
        slidingWindowSize: 3
        minimumNumberOfCalls: 2
        waitDurationInOpenState: 50s