spring:
  application:
    name: payment-ms
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://database-spring.ckfn4cplhgge.us-east-1.rds.amazonaws.com:5432/database_spring?currentSchema=payment
    username: postgres
    password: 12345678
  flyway:
    defaultSchema: payment
    
server:
  port: 80
