name: continuous Integration with github actions

on:
  push:
    branches: 
      - master 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven
        
    - name: Login to Docker hub
      uses: docker/login-action@v2.0.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build application JAR
    - working-directory: ./newPayment
      run: mvn clean package 
      
    - name: Docker Build 
    - working-directory: ./newPayment
      run: docker compose build
      
    - name: Push To Docker Hub Container Registry
      run:  |
        docker tag ${{ secrets.DOCKER_USERNAME }}/new_payment:latest ${{ secrets.DOCKER_USERNAME }}/new_payment:${{ github.run_id }}

        docker push ${{ secrets.DOCKER_USERNAME }}/new_payment:${{ github.run_id }}
        docker push ${{ secrets.DOCKER_USERNAME }}/new_payment:latest
